# generated by datamodel-codegen:
#   filename:  companycam_openapi.yaml
#   timestamp: 2026-04-16T13:44:44+00:00

from __future__ import annotations

from typing import Annotated, Any, Literal

from pydantic import BaseModel, Field


class Address(BaseModel):
    street_address_1: str | None = None
    street_address_2: str | None = None
    city: str | None = None
    state: str | None = None
    postal_code: str | None = None
    country: str | None = None


class Tag(BaseModel):
    id: Annotated[str, Field(description="A unique ID for the Tag.", examples=["48892885"])]
    company_id: Annotated[
        str | None,
        Field(
            description="A unique ID for the Company the Tag belongs to",
            examples=["8292212"],
        ),
    ] = None
    display_value: Annotated[
        str | None,
        Field(
            description="The display value of the Tag. Used to display to the user",
            examples=["Front Side"],
        ),
    ] = None
    value: Annotated[
        str | None,
        Field(
            description="The lowercase version of the display_value. This is useful for searching and sorting",
            examples=["front side"],
        ),
    ] = None
    created_at: Annotated[
        int | None,
        Field(
            description="Timestamp when the Tag was created on the server",
            examples=[1152230608],
        ),
    ] = None
    updated_at: Annotated[
        int | None,
        Field(description="Timestamp when the Tag was last updated", examples=[1152230700]),
    ] = None


class Webhook(BaseModel):
    id: Annotated[str, Field(description="A unique ID for the Webhook.")]
    company_id: Annotated[
        str | None,
        Field(description="A unique ID for the Company the Webhook belongs to"),
    ] = None
    url: Annotated[
        str | None,
        Field(
            description="The URL of the webhook, which will receive requests with data for any events fired that fall within the scopes of the Webhook."
        ),
    ] = None
    scopes: Annotated[
        list[str] | None,
        Field(description="A list of scopes covering events the Webhook is subscripted to."),
    ] = None
    token: Annotated[
        str | None,
        Field(description="A string used to hash the webhook body for verification."),
    ] = None
    enabled: Annotated[
        bool | None, Field(description="Whether or not the Webhook is enabled/active.")
    ] = None
    created_at: Annotated[
        int | None,
        Field(description="Timestamp when the Webhook was created on the server"),
    ] = None
    updated_at: Annotated[
        int | None, Field(description="Timestamp when the Webhook was last updated")
    ] = None


class ImageURI(BaseModel):
    type: str
    uri: str
    url: str | None = None


class SubTask(BaseModel):
    id: Annotated[
        str | None,
        Field(description="The unique ID for the Task", examples=["4782987471"]),
    ] = None
    label: Annotated[
        str | None,
        Field(description="The title of the Task", examples=["Check the roof"]),
    ] = None
    answer_type: Annotated[
        Literal["open_text", "multiple_choice", "yes_no"] | None,
        Field(
            description="The type of answer expected for the SubTask",
            examples=["open_text"],
        ),
    ] = None
    answer_choices: Annotated[
        list[Any] | None,
        Field(
            description="The index from the answer_options array that were selected as answers",
            examples=[[0, 2]],
        ),
    ] = None
    answer_options: Annotated[
        list[str] | None,
        Field(description="A collection of answer options for the SubTask"),
    ] = None
    position: Annotated[
        int | None,
        Field(description="The position for the SubTask within its Task", examples=[2]),
    ] = None
    task_id: Annotated[
        str | None,
        Field(
            description="A unique identifier for the Task the SubTask belongs to",
            examples=["4782987471"],
        ),
    ] = None
    answer_text: Annotated[
        str | None,
        Field(
            description="The answer text for the SubTask when the type is open_text",
            examples=["It was a pretty ok task"],
        ),
    ] = None


class ChecklistTemplate(BaseModel):
    id: Annotated[
        str | None,
        Field(
            description="The unique ID for the ChecklistTemplate",
            examples=["4782987471"],
        ),
    ] = None
    company_id: Annotated[
        str | None,
        Field(
            description="A unique identifier for the Company the ChecklistTemplate belongs to",
            examples=["8292212"],
        ),
    ] = None
    name: Annotated[
        str | None,
        Field(
            description="The name for the ChecklistTemplate",
            examples=["Roof state survey"],
        ),
    ] = None
    description: Annotated[
        str | None,
        Field(
            description="The description for the ChecklistTemplate",
            examples=["A list to make sure everything was properly done"],
        ),
    ] = None
    created_at: Annotated[
        int | None,
        Field(
            description="Timestamp when the ChecklistTemplate was created on the server.",
            examples=[1152230608],
        ),
    ] = None
    updated_at: Annotated[
        int | None,
        Field(
            description="Timestamp when the ChecklistTemplate was last updated",
            examples=[1152230400],
        ),
    ] = None


class Coordinate(BaseModel):
    lat: float
    lon: float


class ProjectIntegration(BaseModel):
    type: Annotated[str, Field(examples=["JobNimbus"])]
    relation_id: Annotated[str, Field(examples=["123"])]


class Comment(BaseModel):
    id: Annotated[str, Field(description="The unique ID of the comment", examples=["4782987471"])]
    creator_id: Annotated[
        str | None,
        Field(
            description="The id of the entity that created the Comment",
            examples=["2789583992"],
        ),
    ] = None
    creator_type: Annotated[
        str | None,
        Field(
            description="The type of the entity that created the Comment",
            examples=["User"],
        ),
    ] = None
    creator_name: Annotated[
        str | None,
        Field(
            description="The display name of the entity that created the Comment",
            examples=["Shawn Spencer"],
        ),
    ] = None
    commentable_id: Annotated[
        str | None,
        Field(
            description="The unique ID of the entity that the comment was applied to",
            examples=["388472672"],
        ),
    ] = None
    commentable_type: Annotated[
        str | None,
        Field(
            description="The type of the entity that the comment was applied to.",
            examples=["Photo"],
        ),
    ] = None
    status: Annotated[
        str | None,
        Field(description="This should always be active", examples=["active"]),
    ] = None
    content: Annotated[
        str | None,
        Field(
            description="The contents of the comment. This may contain whitespace characters such as newlines.",
            examples=["Have you seen this yet?"],
        ),
    ] = None
    created_at: Annotated[
        int | None,
        Field(
            description="Timestamp when the Comment was created on the server",
            examples=[1152230608],
        ),
    ] = None
    updated_at: Annotated[
        int | None,
        Field(
            description="Timestamp when the Comment was last updated",
            examples=[1152230400],
        ),
    ] = None


class Document(BaseModel):
    id: Annotated[str, Field(description="The unique ID of the document", examples=["115"])]
    creator_id: Annotated[
        str | None,
        Field(
            description="The unique ID of the entity that created the document",
            examples=["8675309"],
        ),
    ] = None
    creator_type: Annotated[
        str | None,
        Field(
            description="The type of the entity that created the document",
            examples=["User"],
        ),
    ] = None
    creator_name: Annotated[
        str | None,
        Field(
            description="The unique ID of the company that owns the document",
            examples=["CompanyCam Developer"],
        ),
    ] = None
    project_id: Annotated[
        str | None,
        Field(
            description="The unique ID of the project the document is attached to",
            examples=["48892885"],
        ),
    ] = None
    name: Annotated[
        str | None,
        Field(
            description="the filename of the document",
            examples=["silver-kadabra-measurements.pdf"],
        ),
    ] = None
    url: Annotated[
        str | None,
        Field(
            description="The URL where the document can be downloaded/viewed from",
            examples=[
                "https://static.companycam.com/documents/8374c65e-2048-41d4-b4a7-a9c839fd388a.pdf"
            ],
        ),
    ] = None
    content_type: Annotated[
        str | None,
        Field(
            description="The content type of the document. (e.g. application/pdf)",
            examples=["application/pdf"],
        ),
    ] = None
    byte_size: Annotated[
        int | None,
        Field(description="The size of the document in bytes.", examples=[3457903]),
    ] = None
    created_at: Annotated[
        int | None,
        Field(
            description="Timestamp when the Document was created on the server",
            examples=[1621857746],
        ),
    ] = None
    updated_at: Annotated[
        int | None,
        Field(
            description="Timestamp when the Document was last updated",
            examples=[1621857746],
        ),
    ] = None


class ProjectContactResponse(BaseModel):
    id: Annotated[
        str | None,
        Field(description="The unique ID of the project contact", examples=["115"]),
    ] = None
    project_id: Annotated[
        str | None,
        Field(
            description="The unique ID of the project the contact is attached to",
            examples=["48892885"],
        ),
    ] = None
    name: Annotated[
        str | None, Field(description="The name of the contact", examples=["Joe Smith"])
    ] = None
    email: Annotated[
        str | None,
        Field(
            description="The email of the contact",
            examples=["joe.smith@companycam.com"],
        ),
    ] = None
    phone_number: Annotated[
        str | None,
        Field(description="The phone of the contact", examples=["402-555-1212"]),
    ] = None
    created_at: Annotated[
        int | None,
        Field(
            description="Timestamp when the Project Contact was created on the server",
            examples=[1621857746],
        ),
    ] = None
    updated_at: Annotated[
        int | None,
        Field(
            description="Timestamp when the Project Contact was last updated",
            examples=[1621857746],
        ),
    ] = None


class Error(BaseModel):
    errors: Annotated[list[str] | None, Field(examples=[["Record not found"]])] = None


class ProjectContactRequest(BaseModel):
    name: Annotated[str, Field(description="The name of the contact", examples=["Joe Smith"])]
    email: Annotated[
        str | None,
        Field(
            description="The email of the contact",
            examples=["joe.smith@companycam.com"],
        ),
    ] = None
    phone_number: Annotated[
        str | None,
        Field(description="The phone of the contact", examples=["402-555-1212"]),
    ] = None


class ProjectNotepad(BaseModel):
    notepad: str


class ProjectCollaborator(BaseModel):
    id: Annotated[
        str | None,
        Field(description="The unique ID of the collaborator", examples=["48892885"]),
    ] = None
    company_id: Annotated[
        str | None,
        Field(
            description="The unique ID of the collaborating company",
            examples=["48892885"],
        ),
    ] = None
    project_id: Annotated[
        str | None,
        Field(
            description="The unique ID of the project the collaborator is a part of",
            examples=["48892885"],
        ),
    ] = None
    project_invitation_id: Annotated[
        str | None,
        Field(
            description="The unique ID of the invitation for the collaboration",
            examples=["48892885"],
        ),
    ] = None
    accepted_at: Annotated[
        int | None,
        Field(
            description="Timestamp when the project collaboration was accepted",
            examples=[1621857746],
        ),
    ] = None
    created_at: Annotated[
        int | None,
        Field(
            description="Timestamp when the project collaboration was created on the server",
            examples=[1621857746],
        ),
    ] = None
    updated_at: Annotated[
        int | None,
        Field(
            description="Timestamp when the project collaboration was last updated",
            examples=[1621857746],
        ),
    ] = None


class ProjectInvitation(BaseModel):
    id: Annotated[
        str | None,
        Field(description="The unique ID of invitation", examples=["48892885"]),
    ] = None
    project_id: Annotated[
        str | None,
        Field(description="The unique ID of the project", examples=["48892885"]),
    ] = None
    invite_url: Annotated[
        str | None,
        Field(
            description="The invite url to accept the invitation",
            examples=["https://l.cmpy.cam/P8EfEmTSB4BbrKUgsd"],
        ),
    ] = None
    status: Annotated[
        Literal["accepted", "expired", "pending"] | None,
        Field(
            description="The status of the invitation. It will be one of `accepted`, `expired`, or `pending`"
        ),
    ] = None
    accepted_at: Annotated[
        int | None,
        Field(
            description="Timestamp when the project invitation was accepted",
            examples=[1621857746],
        ),
    ] = None
    accepted_by_id: Annotated[
        str | None,
        Field(
            description="The unique ID of the company who accepted the invitation",
            examples=["48892885"],
        ),
    ] = None
    expires_at: Annotated[
        int | None,
        Field(
            description="Timestamp when the project invitation expires",
            examples=[1621857746],
        ),
    ] = None
    creator_id: Annotated[
        str | None,
        Field(
            description="The unique ID of the user who created the invitation",
            examples=["48892885"],
        ),
    ] = None
    created_at: Annotated[
        int | None,
        Field(
            description="Timestamp when the project invitation was created on the server",
            examples=[1621857746],
        ),
    ] = None
    updated_at: Annotated[
        int | None,
        Field(
            description="Timestamp when the project invitation was last updated",
            examples=[1621857749],
        ),
    ] = None


class Company(BaseModel):
    id: Annotated[str, Field(description="The Company's unique ID", examples=["2789583992"])]
    name: Annotated[str, Field(description="The name of the company", examples=["Psych"])]
    status: Annotated[
        Literal["active", "cancelled", "deleted"] | None,
        Field(description="Indicates the status of the Company.", examples=["active"]),
    ] = None
    address: Annotated[
        Address | None,
        Field(
            description="The address of the company",
            examples=[
                {
                    "street_address_1": "808 P St",
                    "city": "Lincoln",
                    "state": "NE",
                    "postal_code": "68508",
                    "country": "US",
                }
            ],
        ),
    ] = None
    logo: Annotated[
        list[ImageURI] | None,
        Field(description="A list of images for the different variants of the logo"),
    ] = None


class User(BaseModel):
    id: Annotated[str, Field(examples=["2789583992"])]
    company_id: Annotated[str | None, Field(examples=["8292212"])] = None
    email_address: Annotated[str | None, Field(examples=["shawn@psych.co"])] = None
    status: Annotated[
        Literal["active", "deleted"] | None,
        Field(description="Indicates the status of the Company.", examples=["active"]),
    ] = None
    first_name: Annotated[str | None, Field(examples=["Shawn"])] = None
    last_name: Annotated[str | None, Field(examples=["Spencer"])] = None
    profile_image: Annotated[
        list[ImageURI] | None,
        Field(description="A list of images for the different variants of the user profile image"),
    ] = None
    phone_number: Annotated[str | None, Field(examples=["4025551212"])] = None
    created_at: Annotated[int | None, Field(examples=[1490737206])] = None
    updated_at: Annotated[int | None, Field(examples=[1490737206])] = None
    user_url: Annotated[str | None, Field(examples=["https://app.companycam.com/users/1234"])] = (
        None
    )


class Project(BaseModel):
    id: Annotated[
        str,
        Field(description="A unique identifier for the Project.", examples=["94772883"]),
    ]
    company_id: Annotated[
        str | None,
        Field(
            description="A unique identifier for the Company the Project belongs to",
            examples=["8292212"],
        ),
    ] = None
    creator_id: Annotated[
        str | None,
        Field(
            description="The id of the entity that created the Project",
            examples=["2789583992"],
        ),
    ] = None
    creator_type: Annotated[
        str | None,
        Field(
            description="The type of the entity that created the Project",
            examples=["User"],
        ),
    ] = None
    creator_name: Annotated[
        str | None,
        Field(
            description="The display name of the entity that created the Project",
            examples=["Shawn Spencer"],
        ),
    ] = None
    status: Annotated[
        Literal["active", "deleted"] | None,
        Field(description="Indicates the status of the Project.", examples=["active"]),
    ] = None
    archived: Annotated[
        bool | None,
        Field(description="Indicates whether the Project is archived", examples=[False]),
    ] = None
    name: Annotated[
        str | None,
        Field(description="The title of the Project", examples=["Psych Office"]),
    ] = None
    address: Address | None = None
    coordinates: Coordinate | None = None
    featured_image: Annotated[
        list[ImageURI] | None,
        Field(
            description="A list of images for the different variants of the Project's feature image.",
            examples=[
                [
                    {
                        "type": "original",
                        "url": "https://static.companycam.com/VuS0rPvrnNA1490797262.jpg",
                    },
                    {
                        "type": "web",
                        "url": "https://static.companycam.com/VuS0rPvrnNA1490797262web.jpg",
                    },
                    {
                        "type": "thumbnail",
                        "url": "https://static.companycam.com/VuS0rPvrnNA1490797262small.jpg",
                    },
                ]
            ],
        ),
    ] = None
    project_url: Annotated[
        str | None,
        Field(
            description="The URL to the Project in the web app",
            examples=["https://app.companycam.com/projects/1234"],
        ),
    ] = None
    embedded_project_url: Annotated[
        str | None,
        Field(
            description="The URL to an embeddable photo feed for the Project",
            examples=["https://app.companycam.com/embed/projects/QrL2XjgF8P2dN6MPDRdV2Q"],
        ),
    ] = None
    integrations: Annotated[
        list[ProjectIntegration] | None,
        Field(description="A list of integrations associated with the Project"),
    ] = None
    slug: Annotated[
        str | None,
        Field(
            description="A unique identifier use the Project that is used to construct some public URLs",
            examples=["QrL2XjgF8P2dN6MPDRdV2Q"],
        ),
    ] = None
    public: Annotated[
        bool | None,
        Field(
            description="Indicates whether the Project's timeline and other public features are enabled",
            examples=[False],
        ),
    ] = None
    geofence: Annotated[
        list[Coordinate] | None,
        Field(description="The Geofence latitude and longitude"),
    ] = None
    primary_contact: ProjectContactResponse | None = None
    notepad: Annotated[
        str | None,
        Field(
            description="Notes or description of the project",
            examples=["Be sure to let the client know when the work is finished"],
        ),
    ] = None
    created_at: Annotated[
        int | None,
        Field(description="Timestamp when the Project was created", examples=[1152230400]),
    ] = None
    updated_at: Annotated[
        int | None,
        Field(description="Timestamp when the Project was updated", examples=[1395792000]),
    ] = None


class Photo(BaseModel):
    id: Annotated[str, Field(description="The unique ID for the photo", examples=["4782987471"])]
    company_id: Annotated[
        str | None,
        Field(
            description="A unique identifier for the Company the Photo belongs to",
            examples=["8292212"],
        ),
    ] = None
    creator_id: Annotated[
        str | None,
        Field(
            description="The id of the entity that created the Photo",
            examples=["2789583992"],
        ),
    ] = None
    creator_type: Annotated[
        str | None,
        Field(
            description="The type of the entity that created the Photo",
            examples=["User"],
        ),
    ] = None
    creator_name: Annotated[
        str | None,
        Field(
            description="The display name of the entity that created the Photo",
            examples=["Shawn Spencer"],
        ),
    ] = None
    project_id: Annotated[
        str | None,
        Field(
            description="The unique ID of the project the Photo was captured at",
            examples=["94772883"],
        ),
    ] = None
    processing_status: Annotated[
        Literal["pending", "processing", "processed", "processing_error", "duplicate"] | None,
        Field(
            description="Indicates the Photo's processing status.",
            examples=["processed"],
        ),
    ] = None
    coordinates: Annotated[
        list[Coordinate] | None,
        Field(description="The coordinates where the Photo was captured"),
    ] = None
    uris: Annotated[
        list[ImageURI] | None,
        Field(
            description="A list of URIs for the different size variants of the photo.",
            examples=[
                [
                    {
                        "type": "original",
                        "url": "https://static.companycam.com/VuS0rPvrnNA1490797262.jpg",
                    },
                    {
                        "type": "web",
                        "url": "https://static.companycam.com/VuS0rPvrnNA1490797262web.jpg",
                    },
                    {
                        "type": "thumbnail",
                        "url": "https://static.companycam.com/VuS0rPvrnNA1490797262small.jpg",
                    },
                ]
            ],
        ),
    ] = None
    hash: Annotated[
        str | None,
        Field(
            description="The MD5 hash of the photo",
            examples=["00ab337b7399151e5d4aa3bd4226e8dd"],
        ),
    ] = None
    description: Annotated[
        str | None,
        Field(
            description="A description of the photo",
            examples=["The front of the house"],
        ),
    ] = None
    internal: Annotated[
        bool | None,
        Field(
            description="Indicates whether the photo is for internal use only and should not be used in marketing or other public materials",
            examples=[False],
        ),
    ] = None
    photo_url: Annotated[
        str | None,
        Field(
            description="The link to the photo in the web app",
            examples=["https://app.companycam.com/photos/8675309"],
        ),
    ] = None
    captured_at: Annotated[
        int | None,
        Field(description="Timestamp when the Photo was captured", examples=[1152230396]),
    ] = None
    created_at: Annotated[
        int | None,
        Field(
            description="Timestamp when the photo was created on the server. This may differ from the captured_at field",
            examples=[1152230608],
        ),
    ] = None
    updated_at: Annotated[
        int | None,
        Field(
            description="Timestamp when the photo was last updated",
            examples=[1152230400],
        ),
    ] = None


class Group(BaseModel):
    id: Annotated[str, Field(description="A unique ID for the Group.", examples=["3992883"])]
    company_id: Annotated[
        str | None,
        Field(
            description="A unique ID for the Company the Group belongs to",
            examples=["8292212"],
        ),
    ] = None
    name: Annotated[
        str | None,
        Field(description="The title of the Group", examples=["The Psych Crew"]),
    ] = None
    users: Annotated[list[User] | None, Field(description="A list of the group's users")] = None
    status: Annotated[
        Literal["active", "deleted"] | None,
        Field(description="Indicates the status of the Group", examples=["active"]),
    ] = None
    group_url: Annotated[
        str | None,
        Field(
            description="The link to the group in the web app",
            examples=["https://app.companycam.com/groups/1234"],
        ),
    ] = None
    created_at: Annotated[
        int | None,
        Field(
            description="Timestamp when the Group was created on the server",
            examples=[1490737206],
        ),
    ] = None
    updated_at: Annotated[
        int | None,
        Field(
            description="Timestamp when the Group was last updated",
            examples=[1490737744],
        ),
    ] = None


class Task(BaseModel):
    id: Annotated[
        str | None,
        Field(description="The unique ID for the Task", examples=["4782987471"]),
    ] = None
    completed_at: Annotated[
        int | None,
        Field(
            description="Timestamp when the Task was marked completed.",
            examples=[1152230608],
        ),
    ] = None
    completed_by_id: Annotated[
        str | None,
        Field(
            description="The unique ID for entity that completed the Task",
            examples=["14365"],
        ),
    ] = None
    completed_by_type: Annotated[
        str | None,
        Field(
            description="The type of the entity that marked the Task as completed",
            examples=["User"],
        ),
    ] = None
    created_at: Annotated[
        int | None,
        Field(
            description="Timestamp when the Task was created on the server.",
            examples=[1152230608],
        ),
    ] = None
    creator_id: Annotated[
        str | None,
        Field(
            description="A unique identifier of the creator of the Task",
            examples=["314"],
        ),
    ] = None
    creator_type: Annotated[
        str | None,
        Field(description="The type of the creator of the Task", examples=["User"]),
    ] = None
    details: Annotated[
        str | None,
        Field(description="The details of a Task", examples=["Check the roof for leaks"]),
    ] = None
    photo_capture_required: Annotated[
        bool | None,
        Field(
            description="Flag indicating whether a photo is required to complete the Task",
            examples=[True],
        ),
    ] = None
    position: Annotated[
        int | None,
        Field(
            description="The position for the Task within its ChecklistSection or Checklist",
            examples=[2],
        ),
    ] = None
    todo_list_id: Annotated[
        str | None,
        Field(
            description="A unique identifier for the Checklist the Task belongs to",
            examples=["4782987471"],
        ),
    ] = None
    todo_list_section_id: Annotated[
        str | None,
        Field(
            description="A unique identifier for the ChecklistSection the Task belongs to",
            examples=["12663"],
        ),
    ] = None
    title: Annotated[
        str | None,
        Field(description="The title of the Task", examples=["Check the roof"]),
    ] = None
    updated_at: Annotated[
        int | None,
        Field(
            description="Timestamp when the Checklist was last updated on the server.",
            examples=[1152230608],
        ),
    ] = None
    sub_tasks: Annotated[
        list[SubTask] | None,
        Field(description="A collection of sub-tasks associated to a Task"),
    ] = None
    photos: Annotated[
        list[Photo] | None,
        Field(description="A collection of photos associated to a Task"),
    ] = None


class ChecklistSection(BaseModel):
    id: Annotated[
        str | None,
        Field(
            description="The unique ID for the ChecklistSection",
            examples=["4782987471"],
        ),
    ] = None
    todo_list_id: Annotated[
        str | None,
        Field(
            description="A unique identifier for the Checklist the ChecklistSection belongs to",
            examples=["8292212"],
        ),
    ] = None
    creator_id: Annotated[
        str | None,
        Field(
            description="A unique identifier of the creator of the ChecklistSection",
            examples=["314"],
        ),
    ] = None
    creator_type: Annotated[
        str | None,
        Field(
            description="The type of the creator of the ChecklistSection",
            examples=["User"],
        ),
    ] = None
    creator_name: Annotated[
        str | None,
        Field(
            description="The name of the creator of the ChecklistSection",
            examples=["314"],
        ),
    ] = None
    title: Annotated[
        str | None,
        Field(description="The title of the ChecklistSection", examples=["Section #1"]),
    ] = None
    position: Annotated[
        int | None,
        Field(
            description="The position for the ChecklistSection within the Checklist",
            examples=["0"],
        ),
    ] = None
    tasks: Annotated[
        list[Task] | None,
        Field(description="A collection of tasks associated to a ChecklistSection"),
    ] = None


class Checklist(BaseModel):
    id: Annotated[
        str | None,
        Field(description="The unique ID for the Checklist", examples=["4782987471"]),
    ] = None
    company_id: Annotated[
        str | None,
        Field(
            description="A unique identifier for the Company the Checklist belongs to",
            examples=["8292212"],
        ),
    ] = None
    project_id: Annotated[
        str | None,
        Field(
            description="A unique identifier for the Project the Checklist belongs to",
            examples=["812"],
        ),
    ] = None
    name: Annotated[
        str | None,
        Field(description="The name for the Checklist", examples=["Roof state survey"]),
    ] = None
    created_at: Annotated[
        int | None,
        Field(
            description="Timestamp when the Checklist was created on the server.",
            examples=[1152230608],
        ),
    ] = None
    updated_at: Annotated[
        int | None,
        Field(
            description="Timestamp when the Checklist was last updated",
            examples=[1152230400],
        ),
    ] = None
    completed_at: Annotated[
        int | None,
        Field(
            description="Timestamp when the Checklist was completed",
            examples=[1232230400],
        ),
    ] = None
    creator_id: Annotated[
        str | None,
        Field(
            description="A unique identifier for the creator of the Checklist",
            examples=["314"],
        ),
    ] = None
    checklist_template_id: Annotated[
        str | None,
        Field(
            description="A unique identifier for the template used to create the Checklist",
            examples=["4156"],
        ),
    ] = None
    is_populating: Annotated[
        bool | None,
        Field(
            description="Flag indicating wether the Checklist is still being created or not",
            examples=[False],
        ),
    ] = None
    sectionless_tasks: Annotated[
        list[Task] | None,
        Field(description="A collection of tasks that are not associated with a section"),
    ] = None
    sections: Annotated[
        list[ChecklistSection] | None, Field(description="A collection of sections")
    ] = None
